SUPABASE_URL = "https://zmqbakwsbmmdugaazivt.supabase.co"
SUPABASE_PUBLIC_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptcWJha3dzYm1tZHVnYWF6aXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxMDUzNjksImV4cCI6MjA4MzY4MTM2OX0.Jv24qXEifTlPfkOQEbr_978hec9qgkrkNG3Ctqnh0_U"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptcWJha3dzYm1tZHVnYWF6aXZ0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODEwNTM2OSwiZXhwIjoyMDgzNjgxMzY5fQ.BpO7MCkvGCMAaOjjrtgOeeudzf940_zgUA5Yt3BQgrc"

